apiVersion: v1
kind: Service
metadata:
  name: ms-tipo-de-cambio-svc
  namespace: default
spec:
  selector:
    app: ms-tipo-de-cambio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer