apiVersion: v1
kind: Service
metadata:
  name: myapp-node-svc
  namespace: default
spec:
  selector:
    app: myapp-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer